# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name           = "bitcoinclassic"
description = """
Bitcoin Classic is a (controversial) hard fork to a 2mb blocksize supported by several bitcoin developers.

This eris service will connect into the testnet. 
"""

status = "alpha"

[service]
image          = "quay.io/eris/bitcoinclassic"
data_container = true
ports          = [ "8333:8333", "8334:8334" ]
volumes        = [  ]
environment    = [  ]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
dockerfile = "https://github.com/eris-ltd/eris-services/blob/master/docker/x86/bitcoinclassic/Dockerfile"
repository = "https://github.com/bitcoinclassic/bitcoinclassic"
website = "https://bitcoinclassic.com/"

